# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lunbotu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('img2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=256)),
                ('tel', models.IntegerField(unique=True)),
                ('token', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Wenxuanjuji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=200)),
                ('span', models.CharField(max_length=200)),
                ('b', models.CharField(max_length=200)),
                ('i', models.CharField(max_length=200)),
                ('smallImg', models.CharField(max_length=200)),
                ('bigImg', models.CharField(max_length=200)),
                ('h1', models.CharField(max_length=200)),
                ('h3', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('unm', models.IntegerField()),
            ],
        ),
    ]
