# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-31 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.IntegerField(max_length=20, unique=True),
        ),
    ]
